# Form implementation generated from reading ui file 'gui/if_ventadesk.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1367, 1018)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.orders = QtWidgets.QWidget()
        self.orders.setObjectName("orders")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.orders)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.order_list_container = QtWidgets.QVBoxLayout()
        self.order_list_container.setObjectName("order_list_container")
        self.gridLayout_2.addLayout(self.order_list_container, 0, 0, 1, 1)
        self.tabWidget.addTab(self.orders, "")
        self.conversation = QtWidgets.QWidget()
        self.conversation.setEnabled(True)
        self.conversation.setObjectName("conversation")
        self.tabWidget.addTab(self.conversation, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.order_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.order_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.order_title.setObjectName("order_title")
        self.verticalLayout.addWidget(self.order_title)
        self.order_details = QtWidgets.QListWidget(parent=self.centralwidget)
        self.order_details.setObjectName("order_details")
        self.verticalLayout.addWidget(self.order_details)
        self.update_status = QtWidgets.QPushButton(parent=self.centralwidget)
        self.update_status.setObjectName("update_status")
        self.verticalLayout.addWidget(self.update_status)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1367, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ventadesk"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.orders), _translate("MainWindow", "Toutes les commandes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.conversation), _translate("MainWindow", "Messagerie"))
        self.order_title.setText(_translate("MainWindow", "Détail de la commande"))
        self.update_status.setText(_translate("MainWindow", "Modifier le statut"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
