# Form implementation generated from reading ui file 'gui/status_update_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(758, 298)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 721, 271))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comment_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comment_label.sizePolicy().hasHeightForWidth())
        self.comment_label.setSizePolicy(sizePolicy)
        self.comment_label.setObjectName("comment_label")
        self.verticalLayout_2.addWidget(self.comment_label)
        self.comment_text_edit = QtWidgets.QTextEdit(parent=self.verticalLayoutWidget_3)
        self.comment_text_edit.setObjectName("comment_text_edit")
        self.verticalLayout_2.addWidget(self.comment_text_edit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radio_status_CR = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_3)
        self.radio_status_CR.setObjectName("radio_status_CR")
        self.verticalLayout.addWidget(self.radio_status_CR)
        self.radio_status_CT = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_3)
        self.radio_status_CT.setObjectName("radio_status_CT")
        self.verticalLayout.addWidget(self.radio_status_CT)
        self.radio_status_AA = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_3)
        self.radio_status_AA.setObjectName("radio_status_AA")
        self.verticalLayout.addWidget(self.radio_status_AA)
        self.radio_status_PE = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_3)
        self.radio_status_PE.setObjectName("radio_status_PE")
        self.verticalLayout.addWidget(self.radio_status_PE)
        self.radio_status_AP = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_3)
        self.radio_status_AP.setObjectName("radio_status_AP")
        self.verticalLayout.addWidget(self.radio_status_AP)
        self.radio_status_EX = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_3)
        self.radio_status_EX.setObjectName("radio_status_EX")
        self.verticalLayout.addWidget(self.radio_status_EX)
        self.radio_status_TA = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_3)
        self.radio_status_TA.setObjectName("radio_status_TA")
        self.verticalLayout.addWidget(self.radio_status_TA)
        self.radio_status_AN = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_3)
        self.radio_status_AN.setObjectName("radio_status_AN")
        self.verticalLayout.addWidget(self.radio_status_AN)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Modifier le statut"))
        self.comment_label.setText(_translate("Dialog", "Commentaire explicatif (obligatoire)"))
        self.radio_status_CR.setText(_translate("Dialog", "Créée"))
        self.radio_status_CT.setText(_translate("Dialog", "En cours de traitement"))
        self.radio_status_AA.setText(_translate("Dialog", "En attente d\'approvisionnement"))
        self.radio_status_PE.setText(_translate("Dialog", "En préparation à l\'expédition"))
        self.radio_status_AP.setText(_translate("Dialog", "En attente de paiement"))
        self.radio_status_EX.setText(_translate("Dialog", "Expédiée"))
        self.radio_status_TA.setText(_translate("Dialog", "Traitée"))
        self.radio_status_AN.setText(_translate("Dialog", "Annulée"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
